# This is a basic workflow to help you get started with Actions.

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      working-directory: . 
    steps:
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@0.0.1
     
    - name: "Setup Node.js"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install
      run: |
          npm install -g serverless 
          npm install -D https://artifactory.app.protego.io/cloudguard-serverless-plugin.tgz
          
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Cloudguard Proact 
      run: |
          echo "Current Directory"
          pwd
          ls
          cd ..
          echo "Current Directory"
          pwd
          ls
          cd ..
          echo "Current Directory"
          pwd
          ls
          cd ..
          echo "Current Directory"
          pwd
          ls
          sls package
      working-directory: ${{env.working-directory}}
