# This is a basic workflow to help you get started with Actions.

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      working-directory: . 
    steps:
    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@0.0.1
     
    - name: "Setup Node.js"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install npm
      run: |
          npm install -g serverless 
          npm install -D https://artifactory.app.protego.io/cloudguard-serverless-plugin.tgz

          
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Install Relevant Plugins
      run: |
          npm install --save serverless-finch
          npm install serverless-offline --save-dev
          npm install --save serverless-stack-output
          npm install --save serverless-scriptable-plugin
          npm install --save serverless-cloudguard-plugin
          
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2    
            
    - name: Cloudguard Proact 
      run: |
          ls 
          sls package
      working-directory: ${{env.working-directory}}
