# This is a basic workflow to help you get started with Actions.

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build: 
    runs-on: ubuntu-latest
    env:
      working-directory: . 
    steps:
    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@0.0.1
     
    - name: "Setup Node.js"
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install npm
      run: |
          npm install -g serverless 
          npm install -D https://artifactory.app.protego.io/cloudguard-serverless-plugin.tgz
    - name: Install Relevant Plugins
      run: |
          serverless plugin install serverless-finch 
          serverless plungin install serverless-offline
          serverless plungin install serverless-stack-output
          serverless plungin install serverless-scriptable-plugin
          serverless plungin install serverless-cloudguard-plugin
          
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Cloudguard Proact 
      run: |
          ls 
          sls package
      working-directory: ${{env.working-directory}}
